### ISSUE TITLE
Midi Channel Module not remapping channels correctly

### ISSUE THREAD

**Issue by rupertbates** [kilpatrickaudio/Kilpatrick-Toolbox#2]
Hi, thanks so much for your work on these modules, they are fantastic. However I am running into an issue with the midi channel module seemingly not remapping channels as it should.

I have the following setup (I've included some monitor modules in case it helps with diagnosis):
<img width="416" alt="Screen Shot 2022-06-16 at 13 33 06" src="https://user-images.githubusercontent.com/181371/174071024-c1e5f37f-adf8-41c9-a7d0-c3023bb09d0f.png">

- An input from a midi controller keyboard is sending midi in through an input on channel 1
- This is passed through a Midi Channel  Module which is set up to remap the input channel to channel 2
- This is then output to a hardware synth listening on midi channel 2

However the messages arriving at the synth are still on channel 1 (if I set the synth to listen on channel 1 it plays correctly, but on channel 2 it does not)

I'm on Mac OS 11.6.2 and VCV Rack version 2.0.6

I would really appreciate it if you could offer some idea of what the issue might be.

**Comment by kilpatrickaudio** [comment]
Fixed in latest commit! Thanks for pointing that out. Rack does a weird thing where it will override channels automatically if you don't specifically disable that. Oops!

The 2.0.2 version has been bumped in the library and should be available soon.

**Comment by rupertbates** [comment]
Hi, I don't want to pester but did 2.0.2 get released? I've noticed that there is a commit mentioning 2.0.3 but the VCV library is still showing 2.0.1 as the latest version.

**Comment by kilpatrickaudio** [comment]
No.
